// Copyright 2025 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use aes_gcm_siv::{
    aead::{Aead, Payload},
    Aes128GcmSiv, KeyInit,
};
use anyhow::{anyhow, ensure, Result};
use bssl_crypto::hkdf;
use coset::{
    cbor::value::Value,
    cwt::{ClaimName, ClaimsSet},
    iana, Algorithm, CborSerializable, CoseKey, CoseSign1, KeyOperation, KeyType, Label,
};
use hpke::{
    aead::AesGcm128, kdf::HkdfSha256, kem::X25519HkdfSha256, Deserializable, Kem, OpModeR, OpModeS,
    Serializable,
};
use rand::rngs::OsRng;
use std::cmp::min;

// HPKE Base with X25519 + SHA-256 + AES-128-GCM
const HPKE_BASE_X25519_SHA256_AES128GCM: i64 = -65537;
const AEAD_AES_128_GCM_SIV_FIXED_NONCE: i64 = -65538;

// Private CWT claims; see
// https://github.com/google/federated-compute/blob/main/fcp/protos/confidentialcompute/cbor_ids.md.
const PUBLIC_KEY_CLAIM: i64 = -65537;

// A fixed random nonce, which is safe to reuse because the symmetric key is
// never reused.
static NONCE: [u8; 12] = [0x74, 0xDF, 0x8F, 0xD4, 0xBE, 0x34, 0xAF, 0x64, 0x7F, 0x5E, 0x54, 0xF6];

// The HPKE info field is not used.
static HPKE_INFO: [u8; 0] = [];

/// Derives raw private key material using HKDF-SHA256.
/// Per RFC 5869, the salt should be random and at least as long as the hash (32 bytes).
fn derive_raw_private_key(ikm: &[u8], info: &[u8]) -> Result<Vec<u8>> {
    // Static salt from KMS implementation
    let salt = hkdf::Salt::NonEmpty(&[
        5, 36, 164, 198, 227, 192, 203, 187, 132, 228, 115, 85, 125, 175, 222, 66, 105, 238, 84,
        27, 39, 75, 83, 205, 219, 139, 185, 111, 109, 255, 189, 228,
    ]);

    let prk = hkdf::HkdfSha256::extract(ikm, salt);
    let mut secret = prk.expand::<32>(info);

    // Explicitly set/unset bits per RFC 7748 section 5 for X25519
    // This ensures keys match those generated by boringssl
    secret[0] |= !248;
    secret[31] &= !64;
    secret[31] |= !127;

    Ok(secret.into())
}

/// Derives raw private keys for each HKDF info value.
fn derive_raw_private_keys(
    ikm: &[u8],
    infos: impl IntoIterator<Item = impl AsRef<[u8]>>,
) -> Result<Vec<Vec<u8>>> {
    infos.into_iter().map(|info| derive_raw_private_key(ikm, info.as_ref())).collect()
}

/// Gets the public key from a private key using the hpke crate.
fn get_public_key(private_key: &[u8]) -> Result<Vec<u8>> {
    let sk = <X25519HkdfSha256 as Kem>::PrivateKey::from_bytes(private_key)
        .map_err(|e| anyhow!("Invalid private key: {:?}", e))?;
    let pk = X25519HkdfSha256::sk_to_pk(&sk);
    Ok(pk.to_bytes().to_vec())
}

/// Builds a COSE Key from a private or public key.
fn build_cose_key(key_id: &[u8], info: &[u8], public: bool, key: Vec<u8>) -> Result<Vec<u8>> {
    ensure!(
        true, // always HPKE_BASE_X25519_SHA256_AES128GCM for now
        "unsupported algorithm"
    );

    let key_param = if public { iana::OkpKeyParameter::X } else { iana::OkpKeyParameter::D };
    let key_op = if public { iana::KeyOperation::Encrypt } else { iana::KeyOperation::Decrypt };

    let derived_key_id = get_derived_key_id(key_id, info);

    let cose_key = CoseKey {
        kty: KeyType::Assigned(iana::KeyType::OKP),
        key_id: derived_key_id,
        alg: Some(Algorithm::PrivateUse(HPKE_BASE_X25519_SHA256_AES128GCM)),
        key_ops: [KeyOperation::Assigned(key_op)].into(),
        params: vec![
            (
                Label::Int(iana::OkpKeyParameter::Crv as i64),
                Value::from(iana::EllipticCurve::X25519 as u64),
            ),
            (Label::Int(key_param as i64), Value::Bytes(key)),
        ],
        ..Default::default()
    };

    cose_key.to_vec().map_err(|e| anyhow!("Failed to encode CoseKey: {}", e))
}

/// Returns the derived key id from key_id + first 4 bytes of info.
fn get_derived_key_id(key_id: &[u8], info: &[u8]) -> Vec<u8> {
    [key_id, &info[0..min(4, info.len())]].concat()
}

/// Derives public keys for encryption (HPKE public keys).
pub fn derive_public_keys<I>(key_id: &[u8], ikm: &[u8], infos: I) -> Result<Vec<Vec<u8>>>
where
    I: IntoIterator + Clone,
    I::Item: AsRef<[u8]>,
{
    let private_keys = derive_raw_private_keys(ikm, infos.clone())?;
    infos
        .into_iter()
        .zip(private_keys)
        .map(|(info, private_key)| {
            let public_key = get_public_key(&private_key)?;
            build_cose_key(key_id, info.as_ref(), /* public= */ true, public_key)
        })
        .collect()
}

/// Wraps a symmetric encryption key using HPKE.
///
/// # Return Value
///
/// Returns `Ok((encapped_key, encrypted_symmetric_key))` on success.
fn wrap_symmetric_key(
    symmetric_key: &[u8],
    recipient_public_key: &CoseKey,
    associated_data: &[u8],
) -> Result<(Vec<u8>, Vec<u8>)> {
    // Check that the CoseKey can be used for wrapping.
    if recipient_public_key.kty != KeyType::Assigned(iana::KeyType::OKP)
        || recipient_public_key.alg
            != Some(Algorithm::PrivateUse(HPKE_BASE_X25519_SHA256_AES128GCM))
        || !recipient_public_key.params.iter().any(|(label, value)| {
            label == &Label::Int(iana::OkpKeyParameter::Crv as i64)
                && value == &Value::from(iana::EllipticCurve::X25519 as u64)
        })
    {
        return Err(anyhow!("unsupported CoseKey type"));
    }

    // Extract the raw public key and convert it to a PublicKey.
    let raw_recipient_public_key = recipient_public_key
        .params
        .iter()
        .find(|(label, _)| label == &Label::Int(iana::OkpKeyParameter::X as i64))
        .and_then(|(_, value)| value.as_bytes())
        .ok_or_else(|| anyhow!("CoseKey missing X parameter"))?;
    let public_key = <X25519HkdfSha256 as Kem>::PublicKey::from_bytes(raw_recipient_public_key)
        .map_err(|err| anyhow!("failed to parse recipient public key: {:?}", err))?;

    // Wrap the symmetric key using HPKE single-shot seal.
    let (encapped_key, encrypted_symmetric_key) =
        hpke::single_shot_seal::<AesGcm128, HkdfSha256, X25519HkdfSha256, _>(
            &OpModeS::Base,
            &public_key,
            &HPKE_INFO,
            symmetric_key,
            associated_data,
            &mut OsRng,
        )
        .map_err(|err| anyhow!("failed to seal key: {:?}", err))?;
    Ok((encapped_key.to_bytes().to_vec(), encrypted_symmetric_key))
}

/// Encrypts a message using the two-layer FCP encryption pattern.
///
/// 1. Generate a random 16-byte symmetric key
/// 2. Encrypt plaintext with AES-128-GCM-SIV using the symmetric key + associated_data
/// 3. Wrap the COSE-serialized symmetric key with HPKE using associated_data
///
/// # Return Value
///
/// Returns `Ok((ciphertext, encapped_key, encrypted_symmetric_key))` on success.
pub fn encrypt_message(
    plaintext: &[u8],
    public_key: &CoseKey,
    associated_data: &[u8],
) -> Result<(Vec<u8>, Vec<u8>, Vec<u8>)> {
    // Encrypt the plaintext using AEAD.
    let symmetric_key = Aes128GcmSiv::generate_key(&mut OsRng);
    let cipher = Aes128GcmSiv::new(&symmetric_key);
    let ciphertext = cipher
        .encrypt((&NONCE).into(), Payload { msg: plaintext, aad: associated_data })
        .map_err(|err| anyhow!("failed to encrypt plaintext: {:?}", err))?;

    // Construct and serialize a CoseKey containing the symmetric key material.
    let cose_key = CoseKey {
        kty: KeyType::Assigned(iana::KeyType::Symmetric),
        alg: Some(Algorithm::PrivateUse(AEAD_AES_128_GCM_SIV_FIXED_NONCE)),
        params: vec![(
            Label::Int(iana::SymmetricKeyParameter::K as i64),
            Value::Bytes(symmetric_key.to_vec()),
        )],
        ..Default::default()
    }
    .to_vec()
    .map_err(|err| anyhow!("failed to serialize CoseKey: {}", err))?;

    // Encrypt the symmetric key using HPKE.
    let (encapped_key, encrypted_symmetric_key) =
        wrap_symmetric_key(&cose_key, public_key, associated_data)?;
    Ok((ciphertext, encapped_key, encrypted_symmetric_key))
}

/// Encrypts plaintext using the two-layer FCP encryption.
///
/// # Arguments
/// * `recipient_public_key_bytes` - The recipient's COSE public key (as bytes)
/// * `plaintext` - The data to encrypt
/// * `associated_data` - Additional data to be authenticated (e.g., serialized BlobHeader)
/// * `_info` - HPKE info parameter (unused, kept for API compatibility)
///
/// # Returns
/// `(encapsulated_key, encrypted_symmetric_key, ciphertext, associated_data)` on success
pub fn encrypt_with_two_layer(
    recipient_public_key_bytes: &[u8],
    plaintext: &[u8],
    associated_data: &[u8],
    _info: &[u8],
) -> Result<(Vec<u8>, Vec<u8>, Vec<u8>, Vec<u8>)> {
    // Parse the recipient's COSE public key
    let recipient_cose_key = CoseKey::from_slice(recipient_public_key_bytes)
        .map_err(|e| anyhow!("Failed to parse recipient COSE key: {}", e))?;

    // Use local encrypt_message function
    let (ciphertext, encapsulated_key, encrypted_symmetric_key) =
        encrypt_message(plaintext, &recipient_cose_key, associated_data)?;

    Ok((encapsulated_key, encrypted_symmetric_key, ciphertext, associated_data.to_vec()))
}

/// Generates a new X25519 key pair for testing/simulation.
/// Returns (public_key_cose_bytes, private_key_raw_bytes)
pub fn generate_key_pair(key_id: &[u8]) -> Result<(Vec<u8>, Vec<u8>)> {
    use rand::RngCore;

    // Generate random private key material
    let mut private_key = vec![0u8; 32];
    rand::thread_rng().fill_bytes(&mut private_key);

    // Apply RFC 7748 clamping for X25519
    private_key[0] &= 248;
    private_key[31] &= 127;
    private_key[31] |= 64;

    // Derive public key
    let public_key = get_public_key(&private_key)?;

    // Build COSE key for public key
    let cose_key = CoseKey {
        kty: KeyType::Assigned(iana::KeyType::OKP),
        key_id: key_id.to_vec(),
        alg: Some(Algorithm::PrivateUse(HPKE_BASE_X25519_SHA256_AES128GCM)),
        key_ops: [KeyOperation::Assigned(iana::KeyOperation::Encrypt)].into(),
        params: vec![
            (
                Label::Int(iana::OkpKeyParameter::Crv as i64),
                Value::from(iana::EllipticCurve::X25519 as u64),
            ),
            (Label::Int(iana::OkpKeyParameter::X as i64), Value::Bytes(public_key)),
        ],
        ..Default::default()
    };

    let public_key_cose =
        cose_key.to_vec().map_err(|e| anyhow!("Failed to encode public COSE key: {}", e))?;

    Ok((public_key_cose, private_key))
}

/// Builds a COSE private key from raw key material.
pub fn build_private_cose_key(key_id: &[u8], private_key: &[u8]) -> Result<Vec<u8>> {
    let cose_key = CoseKey {
        kty: KeyType::Assigned(iana::KeyType::OKP),
        key_id: key_id.to_vec(),
        alg: Some(Algorithm::PrivateUse(HPKE_BASE_X25519_SHA256_AES128GCM)),
        key_ops: [KeyOperation::Assigned(iana::KeyOperation::Decrypt)].into(),
        params: vec![
            (
                Label::Int(iana::OkpKeyParameter::Crv as i64),
                Value::from(iana::EllipticCurve::X25519 as u64),
            ),
            (Label::Int(iana::OkpKeyParameter::D as i64), Value::Bytes(private_key.to_vec())),
        ],
        ..Default::default()
    };

    cose_key.to_vec().map_err(|e| anyhow!("Failed to encode private COSE key: {}", e))
}

/// Unwraps a symmetric encryption key that was wrapped using HPKE.
///
/// # Arguments
/// * `encrypted_symmetric_key` - The HPKE-encrypted symmetric key
/// * `serialized_encapped_key` - The encapsulated public key from HPKE seal
/// * `private_key` - The raw private key bytes (32 bytes for X25519)
/// * `associated_data` - Additional authenticated data used during sealing
///
/// # Returns
/// The unwrapped symmetric key (as COSE key bytes) on success.
fn unwrap_symmetric_key(
    encrypted_symmetric_key: &[u8],
    serialized_encapped_key: &[u8],
    private_key: &[u8],
    associated_data: &[u8],
) -> Result<Vec<u8>> {
    let sk = <X25519HkdfSha256 as Kem>::PrivateKey::from_bytes(private_key)
        .map_err(|err| anyhow!("failed to load private key: {:?}", err))?;
    let encapped_key = <X25519HkdfSha256 as Kem>::EncappedKey::from_bytes(serialized_encapped_key)
        .map_err(|err| anyhow!("failed to load encapped key: {:?}", err))?;
    hpke::single_shot_open::<AesGcm128, HkdfSha256, X25519HkdfSha256>(
        &OpModeR::Base,
        &sk,
        &encapped_key,
        &HPKE_INFO,
        encrypted_symmetric_key,
        associated_data,
    )
    .map_err(|err| anyhow!("failed to unwrap symmetric key: {:?}", err))
}

/// Extracts a CoseKey from a CBOR Web Token (CWT).
///
/// KMS returns public keys wrapped in CWTs. This function extracts the
/// actual COSE_Key from the CWT payload.
///
/// Note: No validation is performed on the CWT signature or claims.
pub fn extract_key_from_cwt(cwt: &[u8]) -> Result<CoseKey> {
    CoseSign1::from_slice(cwt)
        .and_then(|cwt| ClaimsSet::from_slice(cwt.payload.as_deref().unwrap_or_default()))
        .map_err(|err| anyhow!("failed to decode CWT claims: {:?}", err))
        .and_then(|claims| {
            claims
                .rest
                .into_iter()
                .find(|(name, _)| name == &ClaimName::PrivateUse(PUBLIC_KEY_CLAIM))
                .ok_or_else(|| anyhow!("missing public key claim"))
        })
        .and_then(|(_, value)| {
            CoseKey::from_slice(
                &value
                    .into_bytes()
                    .map_err(|err| anyhow!("invalid public key claim: {:?}", err))?,
            )
            .map_err(|err| anyhow!("failed to decode CoseKey: {:?}", err))
        })
}

/// Extracts a CoseKey from a CWT and serializes it to bytes.
///
/// Convenience function that combines `extract_key_from_cwt` with serialization.
pub fn extract_key_bytes_from_cwt(cwt: &[u8]) -> Result<Vec<u8>> {
    let cose_key = extract_key_from_cwt(cwt)?;
    cose_key.to_vec().map_err(|e| anyhow!("Failed to serialize COSE key: {:?}", e))
}

/// Decrypts data using a symmetric key obtained from KMS.ReleaseResults.
///
/// KMS.ReleaseResults returns the unwrapped symmetric key (COSE-encoded).
/// This function decrypts the ciphertext directly using that key.
///
/// # Arguments
/// * `ciphertext` - The encrypted data
/// * `associated_data` - The AAD used during encryption
/// * `symmetric_key` - The COSE-encoded symmetric key from KMS.ReleaseResults
///
/// # Returns
/// The decrypted plaintext on success.
pub fn decrypt_with_symmetric_key(
    ciphertext: &[u8],
    associated_data: &[u8],
    symmetric_key: &[u8],
) -> Result<Vec<u8>> {
    // Decode the COSE symmetric key
    let cose_key = CoseKey::from_slice(symmetric_key)
        .map_err(|err| anyhow!("failed to decode COSE symmetric key: {:?}", err))?;

    // Verify it's a symmetric key
    if cose_key.kty != KeyType::Assigned(iana::KeyType::Symmetric) {
        return Err(anyhow!("Expected symmetric COSE key, got {:?}", cose_key.kty));
    }

    // Extract the raw key bytes
    let raw_key = cose_key
        .params
        .iter()
        .find(|(label, _)| label == &Label::Int(iana::SymmetricKeyParameter::K as i64))
        .and_then(|(_, value)| value.as_bytes())
        .ok_or_else(|| anyhow!("COSE symmetric key missing K parameter"))?;

    // Decrypt using AES-128-GCM-SIV with fixed nonce
    let cipher = Aes128GcmSiv::new_from_slice(raw_key)
        .map_err(|err| anyhow!("failed to create cipher from symmetric key: {:?}", err))?;

    cipher
        .decrypt((&NONCE).into(), Payload { msg: ciphertext, aad: associated_data })
        .map_err(|err| anyhow!("failed to decrypt with symmetric key: {:?}", err))
}

/// Decrypts data produced using `encrypt_message`.
///
/// This implements the two-layer FCP decryption pattern:
/// 1. Unwrap the symmetric key using HPKE with the private key
/// 2. Decode the COSE symmetric key
/// 3. Decrypt the ciphertext using AES-128-GCM-SIV
///
/// # Arguments
/// * `ciphertext` - The encrypted message
/// * `ciphertext_associated_data` - The AAD used during encryption (e.g., serialized BlobHeader)
/// * `encrypted_symmetric_key` - The HPKE-encrypted symmetric key
/// * `encrypted_symmetric_key_associated_data` - The AAD used for HPKE unwrap
/// * `serialized_encapped_key` - The encapsulated public key from HPKE seal
/// * `private_key` - The raw private key bytes (32 bytes for X25519)
///
/// # Returns
/// The decrypted plaintext on success.
pub fn decrypt_message(
    ciphertext: &[u8],
    ciphertext_associated_data: &[u8],
    encrypted_symmetric_key: &[u8],
    encrypted_symmetric_key_associated_data: &[u8],
    serialized_encapped_key: &[u8],
    private_key: &[u8],
) -> Result<Vec<u8>> {
    // Step 1: Unwrap the symmetric key using HPKE
    let symmetric_key = unwrap_symmetric_key(
        encrypted_symmetric_key,
        serialized_encapped_key,
        private_key,
        encrypted_symmetric_key_associated_data,
    )?;

    // Step 2: Decode the symmetric key and confirm it's of the expected type
    let cose_key = CoseKey::from_slice(&symmetric_key)
        .map_err(|err| anyhow!("failed to decode CoseKey: {}", err))?;
    if cose_key.kty != KeyType::Assigned(iana::KeyType::Symmetric)
        || cose_key.alg != Some(Algorithm::PrivateUse(AEAD_AES_128_GCM_SIV_FIXED_NONCE))
    {
        return Err(anyhow!("unsupported CoseKey type"));
    }
    let raw_symmetric_key = cose_key
        .params
        .iter()
        .find(|(label, _)| label == &Label::Int(iana::SymmetricKeyParameter::K as i64))
        .and_then(|(_, value)| value.as_bytes())
        .ok_or_else(|| anyhow!("CoseKey missing K parameter"))?;

    // Step 3: Decrypt the ciphertext using AES-128-GCM-SIV
    let cipher = Aes128GcmSiv::new_from_slice(raw_symmetric_key)
        .map_err(|err| anyhow!("failed to load symmetric key: {:?}", err))?;
    cipher
        .decrypt((&NONCE).into(), Payload { msg: ciphertext, aad: ciphertext_associated_data })
        .map_err(|err| anyhow!("failed to decrypt data: {:?}", err))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_derive_and_public_keys() -> Result<()> {
        let ikm = b"test_input_key_material";
        let info = b"test_info";
        let key_id = b"key_id_1";

        // Derive a private key
        let private_key = derive_raw_private_key(ikm, info)?;
        assert_eq!(private_key.len(), 32);

        // Get its public key
        let public_key = get_public_key(&private_key)?;
        assert_eq!(public_key.len(), 32);

        // Build COSE key
        let cose_key_bytes = build_cose_key(key_id, info, true, public_key)?;
        assert!(!cose_key_bytes.is_empty());

        // Derive public keys for multiple infos
        let infos = vec![b"info1".as_ref(), b"info2".as_ref()];
        let public_keys = derive_public_keys(key_id, ikm, infos)?;
        assert_eq!(public_keys.len(), 2);

        Ok(())
    }

    #[test]
    fn test_generate_key_pair() -> Result<()> {
        let key_id = b"test_key";

        let (public_cose, private_raw) = generate_key_pair(key_id)?;

        // Verify key sizes
        assert_eq!(private_raw.len(), 32);
        assert!(!public_cose.is_empty());

        // Verify the COSE key can be parsed
        let parsed = CoseKey::from_slice(&public_cose)
            .map_err(|e| anyhow!("Failed to parse COSE key: {:?}", e))?;
        assert_eq!(parsed.key_id, key_id.to_vec());

        Ok(())
    }

    #[test]
    fn test_encrypt_message() -> Result<()> {
        let key_id = b"test_key";

        // Generate a key pair
        let (public_cose, _private_raw) = generate_key_pair(key_id)?;
        let public_key = CoseKey::from_slice(&public_cose)
            .map_err(|e| anyhow!("Failed to parse COSE key: {:?}", e))?;

        // Encrypt a message
        let plaintext = b"test plaintext data";
        let associated_data = b"test associated data";

        let (ciphertext, encapped_key, encrypted_symmetric_key) =
            encrypt_message(plaintext, &public_key, associated_data)?;

        // Verify outputs
        assert!(!ciphertext.is_empty());
        assert!(!encapped_key.is_empty());
        assert!(!encrypted_symmetric_key.is_empty());

        // Ciphertext should be different from plaintext
        assert_ne!(ciphertext, plaintext);

        Ok(())
    }

    #[test]
    fn test_encrypt_with_two_layer() -> Result<()> {
        let key_id = b"test_key";

        // Generate a key pair
        let (public_cose, _private_raw) = generate_key_pair(key_id)?;

        // Encrypt using two-layer
        let plaintext = b"test plaintext";
        let associated_data = b"blob header data";

        let (encapped_key, encrypted_sym_key, ciphertext, returned_aad) =
            encrypt_with_two_layer(&public_cose, plaintext, associated_data, &[])?;

        // Verify outputs
        assert!(!encapped_key.is_empty());
        assert!(!encrypted_sym_key.is_empty());
        assert!(!ciphertext.is_empty());
        assert_eq!(returned_aad, associated_data);

        Ok(())
    }

    #[test]
    fn test_encrypt_decrypt_roundtrip() -> Result<()> {
        let key_id = b"test_key";

        // Generate a key pair
        let (public_cose, private_raw) = generate_key_pair(key_id)?;
        let public_key = CoseKey::from_slice(&public_cose)
            .map_err(|e| anyhow!("Failed to parse COSE key: {:?}", e))?;

        // Encrypt a message
        let plaintext = b"secret message to encrypt and decrypt";
        let associated_data = b"blob header associated data";

        let (ciphertext, encapped_key, encrypted_symmetric_key) =
            encrypt_message(plaintext, &public_key, associated_data)?;

        // Decrypt the message
        let decrypted = decrypt_message(
            &ciphertext,
            associated_data,
            &encrypted_symmetric_key,
            associated_data, // Same AAD for symmetric key in direct encryption
            &encapped_key,
            &private_raw,
        )?;

        assert_eq!(decrypted, plaintext);

        Ok(())
    }

    #[test]
    fn test_decrypt_with_wrong_key_fails() -> Result<()> {
        let key_id = b"test_key";

        // Generate two key pairs
        let (public_cose, _private_raw) = generate_key_pair(key_id)?;
        let (_, wrong_private_raw) = generate_key_pair(b"wrong_key")?;

        let public_key = CoseKey::from_slice(&public_cose)
            .map_err(|e| anyhow!("Failed to parse COSE key: {:?}", e))?;

        // Encrypt a message
        let plaintext = b"secret message";
        let associated_data = b"blob header";

        let (ciphertext, encapped_key, encrypted_symmetric_key) =
            encrypt_message(plaintext, &public_key, associated_data)?;

        // Try to decrypt with wrong key - should fail
        let result = decrypt_message(
            &ciphertext,
            associated_data,
            &encrypted_symmetric_key,
            associated_data,
            &encapped_key,
            &wrong_private_raw,
        );

        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("failed to unwrap symmetric key"));

        Ok(())
    }
}
